### ISSUE TITLE
Only one neighour is considered?

### ISSUE THREAD

**Issue by guyguygang** [liaopeiyuan/GAL#2]
Hi,
Really nice work! When I read the code of neighbor classifer, the way it collects the neighbor embedding confuses me. It seems that in this code only one of  the neighbors is used to infer the node attributes. Is it the original design?

--------
        for user in user_np:
            for i in self.G.neighbors(user):
                neighbor.append(i)
                break
---------

Looking forward to your reply!

**Comment by liaopeiyuan** [comment]
yes, for a node, we heuristically select a neighbor's embedding to defend
